The authorised_user should not be checked for slaves
This breaks the slave in OpenShift:
```
Traceback (most recent call last):
 File "/usr/local/bin/generate_tiles", line 11, in <module>
   load_entry_point('tilecloud-chain', 'console_scripts', 'generate_tiles')()
 File "/app/tilecloud_chain/generate.py", line 468, in main
   gene.config['generation']['authorised_user'] != getuser():
 File "/usr/lib/python3.7/getpass.py", line 169, in getuser
   return pwd.getpwuid(os.getuid())[0]
KeyError: 'getpwuid(): uid not found: 1000270000'
```